# External Dataset Configuration for CodeContextBench
#
# This file defines external datasets (codebases, corpora) used by benchmarks.
# Datasets are not version-controlled; instead, we reference them via symlinks
# or environment variables and define their expected structure and requirements.

datasets:
  ccb_crossrepo:
    # Name and human-readable description
    name: "10Figure Codebases"
    description: "Real-world codebase corpus for evaluating code understanding and agent capabilities. Contains curated OSS repositories (Kubernetes, Firefox, etc.) with standardized task definitions."
    
    # Container image for this dataset
    image: "harbor-ccb_crossrepo:base"
    image_description: "Harbor base image with 10Figure corpus, validator, and task runner pre-installed"
    
    # Environment variable for corpus location
    env_var: "HARBOR_10FIGURE"
    env_default: "/ccb_crossrepo"
    
    # Corpus structure (once mounted/extracted)
    structure:
      root_path: "/ccb_crossrepo"
      subdirectories:
        src: "Source repositories (e.g., /ccb_crossrepo/src/kubernetes)"
        tasks: "Task definitions in YAML format (e.g., /ccb_crossrepo/tasks/cross_file_reasoning_01.yaml)"
        scripts: "Validator and utility scripts (e.g., /ccb_crossrepo/scripts/validate_patch.py)"
    
    # Task types supported by this corpus
    task_types:
      - "cross_file_reasoning"
      - "refactor_rename"
      - "api_upgrade"
      - "bug_localization"
    
    # Task definition schema
    task_format:
      source: "YAML"
      conversion_tool: "runners/gen_harbor_tasks.py"
      generated_files:
        - "instruction.md"        # Human-readable task description (type-specific)
        - "task.toml"             # Harbor task metadata
        - "task.yaml"             # 10Figure task definition with fixed paths
        - "environment/Dockerfile"  # Container setup
        - "tests/test.sh"         # Validation script (Jinja2 rendered)
        - "repo_path"             # Path to repository in container
    
    # Validator configuration
    validator:
      path: "/ccb_crossrepo/scripts/validate_patch.py"
      input_patch: "/logs/agent/patch.diff"
      output_result: "/logs/verifier/validation_result.json"
      output_reward: "/logs/verifier/reward.txt"
      scoring_method: "ground_truth"
    
    # Setup instructions
    setup:
      description: "10Figure corpus must be available in Harbor container environment"
      methods:
        symlink:
          description: "Symlink corpus into container"
          command: "ln -s /path/to/harbor-ccb_crossrepo-dataset ./ccb_crossrepo"
        mount:
          description: "Mount corpus via Docker/Podman volume"
          command: "podman run -v /path/to/harbor-ccb_crossrepo-dataset:/ccb_crossrepo harbor-ccb_crossrepo:base"
        environment_variable:
          description: "Set environment variable for corpus path"
          env_var: "HARBOR_10FIGURE=/path/to/corpus"
    
    # Required environment variables for agent execution
    required_env:
      ANTHROPIC_API_KEY: "Claude API key (required for all agents)"
      SRC_ACCESS_TOKEN: "Sourcegraph API token (required for Claude+MCP agent)"
    
    # Optional environment variables
    optional_env:
      SOURCEGRAPH_URL: "Sourcegraph instance URL (defaults to https://sourcegraph.sourcegraph.com)"
      TEN_FIGURE_CODEBASES_PATH: "Alias for HARBOR_10FIGURE (for compatibility)"
    
    # Size and resource requirements
    resource_requirements:
      disk_size_gb: 5
      corpus_download_url: "Internal: /Users/sjarmak/harbor-ccb_crossrepo-dataset"
      estimated_task_runtime_minutes: "10-15 per task"
    
    # Example task generation command
    example_generation:
      command: "python3 runners/gen_harbor_tasks.py --input <corpus>/tasks --output benchmarks/ccb_crossrepo --templates benchmarks/ccb_crossrepo/templates --repo kubernetes --corpus-root /ccb_crossrepo"
      result: "Generates 4+ Harbor tasks in benchmarks/ccb_crossrepo/ directory"
    
    # Reference documentation
    documentation:
      - "docs/10FIGURE.md"
      - "benchmarks/ccb_crossrepo/README.md"
      - "docs/DEVELOPMENT.md#working-with-benchmarks"
